name: Windows build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v6
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Cache ORT
        id: cache-ort
        uses: actions/cache@v5
        with:
          path: thirdparty/ort/install
          key: ${{ runner.os }}-ort-${{ hashFiles('thirdparty/ort/CMakeLists.txt', 'thirtparty/ort/patches/*') }}

#      - name: Build ORT
#        if: steps.cache-ort.outputs.cache-hit != 'true'
#        run: |
#          cmake -S thirdparty/ort/ -B thirdparty/ort/build/
#          cmake --build thirdparty/ort/build

      - name: Download OpenCV
        run: |
          curl -L -o opencv.zip https://github.com/opencv/opencv/releases/download/4.13.0/opencv-4.13.0-windows.exe
          7z x opencv.zip -oopencv

      - name: Configure
        run: cmake -S . -B build -G Ninja -D PROJECT_VERSION=${{ github.ref_name }} -D OpenCV_DIR=opencv/opencv/build

      - name: Build
        run: cmake --build build --config Release

      - name: Install
        run: cmake --install build --config Release --prefix build/install

      - name: Package
        run: |
          cd build
          cpack -C Release

      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/install

